### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by NickLarsenNZ** [thalo-rs/esdl#3]
I like the look of this crate. I was wondering if there are any plans for syntax highlighting?

**Comment by tqwewe** [comment]
Hi @NickLarsenNZ,

I made a VSCode plugin located in the https://github.com/thalo-rs/esdl-vscode repo, but it's not yet published and not super polished, but works for now.
You'll need to manually install it for now. I'd like to publish it once it's more polished but VSCode syntax highlighting extension development approach was a little strange for me.

**Comment by NickLarsenNZ** [comment]
@tqwewe 

> VSCode syntax highlighting extension development approach was a little strange for me.

Oh yeah, I agree, I just had a quick look - JSON makes it a bit miserable.
